### ISSUE TITLE
自动化学院：请完成自动化学院的专业结构构建

### ISSUE THREAD

**Issue by Jacob953** [Jacob953/evalcsu#2]
**TODO-List**

- [ ] Build the project structure of SOA

**Comment by jzndd** [comment]
已完成

**Comment by Jacob953** [comment]
**Alert**
- 请不要直接修改 main 分支！
- commit 请严格参考 CONTRIBUTION.md ！
- 自动化学院的下层结构尚未搭建，请再次进行检查！

**Comment by jzndd** [comment]
### Done
 -已完成部分自动化学院的下层结构搭建
